include: https://api.choerodon.com.cn/devops/v1/projects/1529/ci_contents/pipelines/690cd18b-ec9e-446c-96c8-54bd4cc1d850/content.yaml

#image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.11.2
#
#stages:
#  - build
#
#build front:
#  stage: build
#  script:
#    - yarn install --registry ${NPM_REPO} --sass-binary-site=http://npm.taobao.org/mirrors/node-sass --ignore-engines
#    - chmod -R 755 node_modules
#    - npm run compile
#    - echo "//${NPM_REGISTRY}:_authToken=${NPM_TOKEN}">.npmrc
#    - npm publish --registry ${NPM_PUBLISH_REGISTRY}
#    - curl -sX POST -F token=${FRONT_REPOSITORY_TOKEN} -F ref=${REF_NAME} https://code.choerodon.com.cn/api/v4/projects/7909/trigger/pipeline
#  only:
#    - tags
#    - master
#    - /^.*hotfix.*$/
#    - /^.*release.*$/